# Generated by Django 3.0.1 on 2019-12-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('user', models.CharField(blank=True, max_length=100)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('n_subm', models.IntegerField(default=0)),
                ('n_s_sub', models.IntegerField(default=0)),
                ('lang', models.CharField(blank=True, max_length=400)),
            ],
        ),
    ]
