# Generated by Django 2.1.7 on 2019-12-25 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='person',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
