# Generated by Django 3.0.1 on 2019-12-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='person',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='ques',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='source_code',
            field=models.CharField(blank=True, max_length=4500),
        ),
    ]
