# Generated by Django 3.0.1 on 2019-12-27 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191227_0933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
